dist: trusty
language: python

git:
  depth: false
  quiet: true

notifications:
  email: false

python:
  - 3.6

# Lua package manager, needed to install luacheck (see below).
addons:
  apt:
    packages:
    - luarocks

cache:
  directories:
    - wesnoth_tools

before_script:
  # Install luacheck (Lua static analyzer)
  - sudo luarocks install luacheck

  # Copy the addon elsewhere, so that wmllint can check it without all the other Wesnoth sources
  # (they will also be in the root directory).
  - rsync --exclude .git --exclude wesnoth_tools -a . Legend_of_the_Invincibles

  # Download Wesnoth tools (if not yet in the cache) from Wesnoth source repository.
  - >
        [ -f wesnoth_tools/COMPLETE ] || (
                # Download Wesnoth core (contains WML linter utility and its dependencies).
                git clone -q --depth 1 https://github.com/wesnoth/wesnoth &&

                # Save tools in the cache.
                # Don't download the entire Wesnoth next time.
                rm -rf wesnoth_tools && mv wesnoth/data/tools wesnoth_tools && touch wesnoth_tools/COMPLETE
        )

script:
# Luacheck is a Lua static analyzer. It notices Lua syntax errors, some typos,
# things like "accessing undefined variable", unused variables, variables that are unexpectedly global, etc.
# Exit code: 0 - success (not even a single warning),
# 1 - there are warnings (shouldn't cause Travis build to fail),
# 2 - some serious errors (syntax errors, etc.),
# 3 - luacheck failed for whatever reason (file not found, etc.).
  - luacheck Legend_of_the_Invincibles/ --std lua53 --globals loti wesnoth wml || [[ $? -le 1 ]]

# wmllint (part of Wesnoth itself) is a static analyzer of WML files.
# It is known for false positives (which can later be countered with special comments),
# so for now its warnings shouldn't cause Travis build to fail.
  - python wesnoth_tools/wmllint -v -d -K Legend_of_the_Invincibles

after_success:
# Upload the daily version of addon (only if we are in a Travis Cron Job or in Triggered Build, not on every commit).
# If there is an environment variable PBL_PASSPHRASE (can be securily specified in Travis interface,
# without making it public), then "passphrase=" in _server.pbl is ignored,
# and value of this environment variable is used instead.
# NOTE: file _server.pbl should be present in the repository (without the passphrase= line).
  - >
        [[ $PBL_PASSPHRASE != "" && ( $TRAVIS_EVENT_TYPE = "cron" || $TRAVIS_EVENT_TYPE = "api" ) && $TRAVIS_BRANCH = "master" ]] &&
        ADDON=Legend_of_the_Invincibles_beta &&
        mv Legend_of_the_Invincibles $ADDON &&
        find $ADDON -type f | xargs sed -i "s@add-ons/Legend_of_the_Invincibles@add-ons/$ADDON@g" &&
        python wesnoth_tools/wesnoth_addon_manager
        -u $ADDON
        --pbl $ADDON/beta.pbl
        --pbl-key passphrase $PBL_PASSPHRASE
        --pbl-key email $PBL_EMAIL
        --pbl-key version $(git describe HEAD --tags | tr '-' '.')
