dist: trusty
language: python

git:
  depth: 1
  quiet: true

notifications:
  email: false

python:
  - 3.6

before_script:
  # Copy the addon elsewhere, so that wmllint can check it without all the other Wesnoth sources
  # (they will also be in the root directory).
  - rsync --exclude .git -a . Legend_of_the_Invincibles

  # Download Wesnoth core (contains WML linter utility and its dependencies).
  - git clone -q --depth 1 https://github.com/wesnoth/wesnoth

  # Apply pull request #3785 - required bugfix for wmllint.
  # Remove this line after https://github.com/wesnoth/wesnoth/pull/3785 gets merged.
  - wget https://raw.githubusercontent.com/wesnoth/wesnoth/fbb79dc94f2af0840cff5ed44b419778fb4c6281/data/tools/wmllint -O wesnoth/data/tools/wmllint

script:
  - python wesnoth/data/tools/wmllint -v -d -K Legend_of_the_Invincibles

after_success:
# Upload the addon as "LotI daily builds" (only if we are in a Travis Cron Job, not on every commit).
# If there is an environment variable PBL_PASSPHRASE (can be securily specified in Travis interface,
# without making it public), then "passphrase=" in _server.pbl is ignored,
# and value of this environment variable is used instead.
# NOTE: file _server.pbl should be present in the repository (without the passphrase= line).
  - >
        [[ $PBL_PASSPHRASE != "" && $TRAVIS_EVENT_TYPE = "cron" && $TRAVIS_BRANCH = "master" ]] &&
        python data/tools/wesnoth_addon_manager
        -u Legend_of_the_Invincibles
        --pbl-key passphrase $PBL_PASSPHRASE
        --pbl-key title "LotI daily builds"
