dist: trusty
language: python

git:
  depth: 1

notifications:
  email: false

python:
  - 3.6

before_script:
  # Copy the addon elsewhere, so that wmllint can check it without all the other Wesnoth sources
  # (they will also be in the root directory).
  - rsync --exclude .git -a . Legend_of_the_Invincibles

  # Download Wesnoth core (contains WML linter utility and its dependencies).
  - git clone --depth 1 https://github.com/wesnoth/wesnoth

  # Apply pull request #3785 - required bugfix for wmllint.
  # Remove this line after https://github.com/wesnoth/wesnoth/pull/3785 gets merged.
  - wget https://raw.githubusercontent.com/wesnoth/wesnoth/fbb79dc94f2af0840cff5ed44b419778fb4c6281/data/tools/wmllint -O wesnoth/data/tools/wmllint

script:
  - python wesnoth/data/tools/wmllint -vv -d -K Legend_of_the_Invincibles
